### ISSUE TITLE
Example is not working

### ISSUE THREAD

**Issue by sushi30** [webb-tools/webb.js#75]
**Describe the bug**
Get syntax error when trying to load the example.

**To Reproduce**
1. `git clone git@github.com:webb-tools/webb.js.git`
2. `cd webb.js/examples/sdk-mixer`
3. `yarn install`
4. `yarn dev`

**Expected behavior**
Application runs without errors.

**Error logs**
```node
// truncated
ERROR in /home/iparan/dev/webb.js/packages/sdk-mixer/src/zkproof.ts
Module build failed (from /home/iparan/dev/webb.js/node_modules/babel-loader/lib/index.js):
SyntaxError: /home/iparan/dev/webb.js/packages/sdk-mixer/src/zkproof.ts: Unexpected reserved word 'public' (5:4)

  3 | export class ZKProof {
  4 |   constructor(
> 5 |     public readonly leafIndexCommitments: Array<Scalar>,
    |     ^
  6 |     public readonly commitments: Array<Scalar>,
  7 |     public readonly proofCommitments: Array<Scalar>,
  8 |     public readonly nullifierHash: Scalar,
    at Parser._raise (/home/iparan/dev/webb.js/node_modules/@babel/parser/lib/index.js:748:17)
    at Parser.raiseWithData (/home/iparan/dev/webb.js/node_modules/@babel/parser/lib/index.js:741:17)
    at Parser.raise (/home/iparan/dev/webb.js/node_modules/@babel/parser/lib/index.js:735:17)
    at Parser.checkReservedWord (/home/iparan/dev/webb.js/node_modules/@babel/parser/lib/index.js:11388:14)
    at Parser.parseIdentifierName (/home/iparan/dev/webb.js/node_modules/@babel/parser/lib/index.js:11350:12)
    at Parser.parseIdentifier (/home/iparan/dev/webb.js/node_modules/@babel/parser/lib/index.js:11317:23)
    at Parser.parseBindingAtom (/home/iparan/dev/webb.js/node_modules/@babel/parser/lib/index.js:9495:17)
    at Parser.parseMaybeDefault (/home/iparan/dev/webb.js/node_modules/@babel/parser/lib/index.js:9557:50)
    at Parser.parseAssignableListItem (/home/iparan/dev/webb.js/node_modules/@babel/parser/lib/index.js:9537:23)
    at Parser.parseBindingList (/home/iparan/dev/webb.js/node_modules/@babel/parser/lib/index.js:9529:24)
    at Parser.parseFunctionParams (/home/iparan/dev/webb.js/node_modules/@babel/parser/lib/index.js:12411:24)
    at Parser.parseMethod (/home/iparan/dev/webb.js/node_modules/@babel/parser/lib/index.js:11154:10)
    at Parser.pushClassMethod (/home/iparan/dev/webb.js/node_modules/@babel/parser/lib/index.js:12701:30)
    at Parser.parseClassMemberWithIsStatic (/home/iparan/dev/webb.js/node_modules/@babel/parser/lib/index.js:12590:12)
    at Parser.parseClassMember (/home/iparan/dev/webb.js/node_modules/@babel/parser/lib/index.js:12532:10)
    at /home/iparan/dev/webb.js/node_modules/@babel/parser/lib/index.js:12477:14
 @ /home/iparan/dev/webb.js/packages/sdk-mixer/src/index.ts 5:0-26 5:0-26
 @ ./src/main.ts
ℹ ｢wdm｣: Failed to compile.
```
see [full error log](https://github.com/webb-tools/webb.js/files/6534303/error.log)

**Desktop (please complete the following information):**
 - OS: WSL2 (Ubuntu 20.4) on Windows 10

**Additional context**
Seems webpack is trying to serve the files as plain javascript without transpiling.
see [full error log](https://github.com/webb-tools/webb.js/files/6534303/error.log)

**Comment by shekohex** [comment]
Thank you for the issue report, I'll take a look asap and try to fix it.
